export const userConstants ={
    LOGIN_SUCCESS : 'LOGIN_SUCCESS', 
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    REGISTER_REQUEST : 'REGISTER_REQUEST',
    REGISTER_FAILURE : 'REGISTER_FAILURE',
    OPEN_EXPENSE_DIALOG : 'OPEN_EXPENSE_DIALOG',
    CLOSE_EXPENSE_DIALOG:'CLOSE_EXPENSE_DIALOG',
    EXPENSE_ERROR:'EXPENSE_ERROR',
    SHOW_SNACKBAR:'SHOW_SNACKBAR'
};